/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.veterinaria.igu;

import java.awt.Color;

/**
 *
 * @author Leo
 */
public class PanelMascota extends javax.swing.JPanel {

    /**
     * Creates new form PanelMascota
     */
    public PanelMascota() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MascotaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnCargarMascota = new javax.swing.JPanel();
        lblCargarMasco2 = new javax.swing.JLabel();
        btnEditarMascota = new javax.swing.JPanel();
        lblCargarMasco = new javax.swing.JLabel();
        btnActualizarMascota = new javax.swing.JPanel();
        lblCargarMasco1 = new javax.swing.JLabel();
        btnEliminarMascota = new javax.swing.JPanel();
        lblCargarMasco3 = new javax.swing.JLabel();
        btnBuscarMascota = new javax.swing.JPanel();
        lblCargarMasco4 = new javax.swing.JLabel();

        MascotaPanel.setBackground(new java.awt.Color(255, 255, 255));
        MascotaPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 2, true));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "perro", "pichu", "caniche", "si", "no", "-", "muerde", "33011"},
                {"14", "gato", "maylu", "siames", "no", "no", "obesidad", null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TIPO", "NOMBRE", "RAZA", "CASTRADO", "ALERGICO", "TRATAMIENTO", "OBS", "DNI CLIENTE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        MascotaPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 810, 510));

        btnCargarMascota.setBackground(new java.awt.Color(0, 102, 204));
        btnCargarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCargarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCargarMascotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCargarMascotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCargarMascotaMouseExited(evt);
            }
        });
        btnCargarMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargarMasco2.setBackground(new java.awt.Color(0, 0, 0));
        lblCargarMasco2.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCargarMasco2.setForeground(new java.awt.Color(255, 255, 255));
        lblCargarMasco2.setText("CARGAR");
        btnCargarMascota.add(lblCargarMasco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, 30));

        MascotaPanel.add(btnCargarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 210, 50));

        btnEditarMascota.setBackground(new java.awt.Color(0, 102, 204));
        btnEditarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMascotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMascotaMouseExited(evt);
            }
        });
        btnEditarMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargarMasco.setBackground(new java.awt.Color(0, 0, 0));
        lblCargarMasco.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCargarMasco.setForeground(new java.awt.Color(255, 255, 255));
        lblCargarMasco.setText("EDITAR");
        btnEditarMascota.add(lblCargarMasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, 30));

        MascotaPanel.add(btnEditarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 210, 50));

        btnActualizarMascota.setBackground(new java.awt.Color(0, 102, 204));
        btnActualizarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarMascotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarMascotaMouseExited(evt);
            }
        });
        btnActualizarMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargarMasco1.setBackground(new java.awt.Color(0, 0, 0));
        lblCargarMasco1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCargarMasco1.setForeground(new java.awt.Color(255, 255, 255));
        lblCargarMasco1.setText("ACTUALIZAR");
        btnActualizarMascota.add(lblCargarMasco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 120, 30));

        MascotaPanel.add(btnActualizarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 210, 50));

        btnEliminarMascota.setBackground(new java.awt.Color(0, 102, 204));
        btnEliminarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMascotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMascotaMouseExited(evt);
            }
        });
        btnEliminarMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargarMasco3.setBackground(new java.awt.Color(0, 0, 0));
        lblCargarMasco3.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCargarMasco3.setForeground(new java.awt.Color(255, 255, 255));
        lblCargarMasco3.setText("ELIMINAR");
        btnEliminarMascota.add(lblCargarMasco3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 30));

        MascotaPanel.add(btnEliminarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 210, 50));

        btnBuscarMascota.setBackground(new java.awt.Color(0, 102, 204));
        btnBuscarMascota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarMascota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMascotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMascotaMouseExited(evt);
            }
        });
        btnBuscarMascota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCargarMasco4.setBackground(new java.awt.Color(0, 0, 0));
        lblCargarMasco4.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        lblCargarMasco4.setForeground(new java.awt.Color(255, 255, 255));
        lblCargarMasco4.setText("BUSCAR");
        btnBuscarMascota.add(lblCargarMasco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 30));

        MascotaPanel.add(btnBuscarMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, 210, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MascotaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MascotaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarMascotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarMascotaMouseClicked
        //btnCargarMascota.setBackground(new Color(21,10,112));
    }//GEN-LAST:event_btnCargarMascotaMouseClicked

    private void btnCargarMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarMascotaMouseEntered
        btnCargarMascota.setBackground(new Color(21,10,112));
    }//GEN-LAST:event_btnCargarMascotaMouseEntered

    private void btnCargarMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCargarMascotaMouseExited
        btnCargarMascota.setBackground(new Color(21,101,192));
    }//GEN-LAST:event_btnCargarMascotaMouseExited

    private void btnEditarMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMascotaMouseEntered
        btnEditarMascota.setBackground(new Color(21,10,112));
    }//GEN-LAST:event_btnEditarMascotaMouseEntered

    private void btnEditarMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMascotaMouseExited
        btnEditarMascota.setBackground(new Color(21,101,192));
    }//GEN-LAST:event_btnEditarMascotaMouseExited

    private void btnEliminarMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMascotaMouseEntered
        btnEliminarMascota.setBackground(new Color(21,10,112));
    }//GEN-LAST:event_btnEliminarMascotaMouseEntered

    private void btnEliminarMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMascotaMouseExited
        btnEliminarMascota.setBackground(new Color(21,101,192));
    }//GEN-LAST:event_btnEliminarMascotaMouseExited

    private void btnBuscarMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMascotaMouseEntered
        btnBuscarMascota.setBackground(new Color(21,10,112));
    }//GEN-LAST:event_btnBuscarMascotaMouseEntered

    private void btnBuscarMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMascotaMouseExited
        btnBuscarMascota.setBackground(new Color(21,101,192));
    }//GEN-LAST:event_btnBuscarMascotaMouseExited

    private void btnActualizarMascotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMascotaMouseEntered
        btnActualizarMascota.setBackground(new Color(21,10,112));
    }//GEN-LAST:event_btnActualizarMascotaMouseEntered

    private void btnActualizarMascotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMascotaMouseExited
        btnActualizarMascota.setBackground(new Color(21,101,192));
    }//GEN-LAST:event_btnActualizarMascotaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MascotaPanel;
    private javax.swing.JPanel btnActualizarMascota;
    private javax.swing.JPanel btnBuscarMascota;
    private javax.swing.JPanel btnCargarMascota;
    private javax.swing.JPanel btnEditarMascota;
    private javax.swing.JPanel btnEliminarMascota;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCargarMasco;
    private javax.swing.JLabel lblCargarMasco1;
    private javax.swing.JLabel lblCargarMasco2;
    private javax.swing.JLabel lblCargarMasco3;
    private javax.swing.JLabel lblCargarMasco4;
    // End of variables declaration//GEN-END:variables
}
