/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.veterinaria.igu;

import com.veterinaria.logica.ControladoraLogica;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Leo
 */
public class Principal extends javax.swing.JFrame {

    ControladoraLogica cl = new ControladoraLogica();
    PanelMascota panelMasco = new PanelMascota();
    PanelClientes panelCli = new PanelClientes();
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLateral = new javax.swing.JPanel();
        btnMascotas = new javax.swing.JPanel();
        lblMascota = new javax.swing.JLabel();
        btnClientes = new javax.swing.JPanel();
        lblMascota1 = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        panelInterior = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLateral.setBackground(new java.awt.Color(13, 71, 161));
        menuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMascotas.setBackground(new java.awt.Color(19, 90, 173));
        btnMascotas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMascotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMascotasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMascotasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMascotasMouseExited(evt);
            }
        });
        btnMascotas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMascota.setBackground(new java.awt.Color(255, 255, 255));
        lblMascota.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lblMascota.setForeground(new java.awt.Color(255, 255, 255));
        lblMascota.setText("MASCOTAS");
        btnMascotas.add(lblMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 50));

        menuLateral.add(btnMascotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 210, 50));

        btnClientes.setBackground(new java.awt.Color(19, 90, 173));
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMascota1.setBackground(new java.awt.Color(255, 255, 255));
        lblMascota1.setFont(new java.awt.Font("Roboto Medium", 1, 24)); // NOI18N
        lblMascota1.setForeground(new java.awt.Color(255, 255, 255));
        lblMascota1.setText("CLIENTES");
        btnClientes.add(lblMascota1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 130, 40));

        menuLateral.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 50));

        getContentPane().add(menuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 730));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInterior.setBackground(new java.awt.Color(255, 255, 255));
        panelInterior.setLayout(new java.awt.BorderLayout());
        panelPrincipal.add(panelInterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1120, 660));

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 1120, 730));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMascotasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotasMouseEntered
        btnMascotas.setBackground(new Color(21,101,192));
        
    }//GEN-LAST:event_btnMascotasMouseEntered

    private void btnMascotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotasMouseClicked
        btnMascotas.setBackground(new Color(21,101,192));
        mostrarPanel(panelMasco);
    }//GEN-LAST:event_btnMascotasMouseClicked

    private void btnClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseClicked
        //btnClientes.setBackground(new Color(21,101,192));
        mostrarPanel(panelCli);
    }//GEN-LAST:event_btnClientesMouseClicked

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        btnClientes.setBackground(new Color(21,101,192));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnMascotasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMascotasMouseExited
        btnMascotas.setBackground(new Color(19,90,173));//[19,90,173]
    }//GEN-LAST:event_btnMascotasMouseExited

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        btnClientes.setBackground(new Color(19,90,173));
    }//GEN-LAST:event_btnClientesMouseExited
    
    private void mostrarPanel(JPanel p){
        p.setSize(1120, 660);
        p.setLocation(0, 0);
        
        panelInterior.removeAll();
        panelInterior.add(p, BorderLayout.CENTER);
        panelInterior.revalidate();
        panelInterior.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal().setVisible(true);
//            }
//        });
//   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClientes;
    private javax.swing.JPanel btnMascotas;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblMascota1;
    private javax.swing.JPanel menuLateral;
    private javax.swing.JPanel panelInterior;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
